'use strict';const crypto=require('crypto');
const STATES=Object.freeze(['lead_created','vehicle_reserved','desking','credit_consented','lender_submitted','documents_ready','signed','delivered','follow_up','cancelled']);
const TRANSITIONS=Object.freeze({lead_created:['vehicle_reserved','cancelled'],vehicle_reserved:['desking','cancelled'],desking:['credit_consented','documents_ready','cancelled'],credit_consented:['lender_submitted','cancelled'],lender_submitted:['documents_ready','cancelled'],documents_ready:['signed','cancelled'],signed:['delivered','cancelled'],delivered:['follow_up'],follow_up:[],cancelled:[]});
const PROVIDERS=Object.freeze(['dms','crm','oem','lender','valuation','esign','payment','messaging']);
class DealError extends Error{constructor(code,message,status=400){super(message);this.code=code;this.status=status;}}
const tenantFor=u=>{if(!u?.id)throw new DealError('AUTH_REQUIRED','Authentication required',401);return String(u.dealer_id||u.tenant_id||u.tenantId||`personal:${u.id}`);};
const requireRole=(u,roles)=>{if(!roles.includes(u.role))throw new DealError('ROLE_FORBIDDEN',`Role ${u.role||'unknown'} is not authorized`,403);};
function normalizeDeal(i={}){const required=['customerId','vehicleId','vin','leadSource'];const missing=required.filter(k=>!i[k]);if(missing.length)throw new DealError('INVALID_DEAL',`Missing: ${missing.join(', ')}`);if(!/^[A-HJ-NPR-Z0-9]{17}$/.test(String(i.vin).toUpperCase()))throw new DealError('INVALID_VIN','VIN must be a valid 17-character identifier');return{customerId:String(i.customerId),vehicleId:String(i.vehicleId),vin:String(i.vin).toUpperCase(),leadSource:String(i.leadSource),consent:{marketing:false,credit:false},tradeInId:i.tradeInId?String(i.tradeInId):null};}
function monthlyPayment(principal,annualRate,months){const p=Number(principal),r=Number(annualRate)/1200,n=Number(months);if(!(p>=0)||!(r>=0)||!Number.isInteger(n)||n<1||n>120)throw new DealError('INVALID_FINANCE_TERMS','Invalid principal, APR, or term');return Number((r===0?p/n:(p*r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1)).toFixed(2));}
function validateTransition(current,next,user,e={}){if(!(TRANSITIONS[current]||[]).includes(next))throw new DealError('INVALID_TRANSITION',`Cannot move ${current} to ${next}`,409);requireRole(user,next==='lender_submitted'?['finance','manager','admin']:next==='delivered'?['manager','delivery','admin']:['sales','finance','manager','delivery','admin']);if(next==='vehicle_reserved'&&(!e.inventorySnapshotId||e.available!==true))throw new DealError('INVENTORY_REQUIRED','Current available inventory snapshot required');if(next==='desking'){if(!(Number(e.sellingPrice)>0)||!(Number(e.advertisedPrice)>0))throw new DealError('PRICE_REQUIRED','Auditable prices required');if(Number(e.sellingPrice)<Number(e.advertisedPrice)*.95&&!e.managerApprovalId)throw new DealError('DISCOUNT_APPROVAL_REQUIRED','Manager approval required above discount threshold');if(e.tradeInAmount&&(!e.valuationProvider||!e.valuationReference))throw new DealError('VALUATION_EVIDENCE_REQUIRED','Trade-in source and reference required');}if(next==='credit_consented'&&(!e.consentId||!e.consentTimestamp||!e.permissiblePurpose))throw new DealError('CREDIT_CONSENT_REQUIRED','Recorded consent and permissible purpose required');if(next==='lender_submitted'&&(!e.applicationDigest||!e.lenderRoutingId))throw new DealError('LENDER_PACKAGE_REQUIRED','Application digest and lender routing required');if(next==='documents_ready'&&(!e.buyerOrderDigest||!e.disclosuresDigest))throw new DealError('DOCUMENTS_REQUIRED','Buyer order and disclosure digests required');if(next==='signed'&&(!e.envelopeId||!e.signatureEventId))throw new DealError('SIGNATURE_EVIDENCE_REQUIRED','E-signature envelope and event required');if(next==='delivered'&&(!e.inventoryReconciliationId||!e.deliveryChecklistId||!e.paymentStatus))throw new DealError('DELIVERY_RECONCILIATION_REQUIRED','Inventory, delivery, and payment reconciliation required');}
const idempotencyKey=k=>{if(!k||!/^[A-Za-z0-9._:-]{8,128}$/.test(k))throw new DealError('IDEMPOTENCY_REQUIRED','Valid Idempotency-Key required');return k;};const digest=d=>crypto.createHash('sha256').update(JSON.stringify(d)).digest('hex');
module.exports={STATES,PROVIDERS,DealError,tenantFor,requireRole,normalizeDeal,monthlyPayment,validateTransition,idempotencyKey,digest};
